name: iOS starter workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build and Test on iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_15.2.app"

      - name: List available schemes
        run: xcodebuild -list

      - name: Build for Testing
        run: |
          PROJECT_NAME="TestUtitTesting"
          SCHEME_NAME="TestUtitTesting"
          DESTINATION="platform=iOS Simulator,name=iPhone 15"

          xcodebuild build-for-testing \
            -project "$PROJECT_NAME.xcodeproj" \
            -scheme "$SCHEME_NAME" \
            -destination "$DESTINATION" \
            -allowProvisioningUpdates \
            -enableCodeCoverage YES \
            | xcbeautify

      - name: Run Tests
        run: |
          PROJECT_NAME="TestUtitTesting"
          SCHEME_NAME="TestUtitTesting"
          DESTINATION="platform=iOS Simulator,name=iPhone 15"

          xcodebuild test-without-building \
            -project "$PROJECT_NAME.xcodeproj" \
            -scheme "$SCHEME_NAME" \
            -destination "$DESTINATION" \
            -enableCodeCoverage YES \
            | xcbeautify

      - name: Upload test logs on failure
        if: failure()
        run: |
          echo "Tests failed. You can add a step to upload logs or artifacts here."

      - name: Install xcbeautify
        run: brew install xcbeautify
